# Commit and push
# https://github.com/actions/checkout#push-a-commit-using-the-built-in-token
name: Commit and push
on: create
jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event.ref_type == 'branch' && github.event.ref == 'main'
    steps:
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
      - uses: actions/checkout@v2
      - name: Create report file
        run: date > report.txt
      - name: Commit and push report
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit -m "Generate automated file"
          git push
